### ISSUE TITLE
Consider picking a license

### ISSUE THREAD

**Issue by sroegner** [jhades/jhades#11]
Please disregard if there is a license in here somewhere - in any case i'd like to see a LICENSE file reflecting the license for the project at the project root. 

https://help.github.com/articles/adding-a-license-to-a-repository/#including-an-open-source-license-in-your-repository

Thank you!

**Comment by vorburger** [comment]
http://jhades.github.io footer says "Code licensed under the MIT License." ...

**Comment by sroegner** [comment]
Thank you.

**Comment by vorburger** [comment]
@sroegner FYI I'm NOT the maintainer of this project, so this (MIT) is just from what I saw on the site.

But I have just proposed #12 to clarify it... hopefully the project maintainer is alive and will review that.

**Comment by sroegner** [comment]
Much appreciated - if nothing else it will help preventing traffic like this ;-)
